services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo_data:/data/db

  server:
    build: ./server
    image: mohamedkhalilzrelly/vermailbs:latest
    container_name: server
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    depends_on:
      - mongodb
    volumes:
      - ./server/src:/app/src
      - ./server/src/data:/app/src/data
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  client:
    build: ./client
    image: mohamedkhalilzrelly/vermailfc:latest
    container_name: client
    restart: always
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - server
    volumes:
      - ./client/src:/app/src
      - ./client/public:/app/public

volumes:
  mongo_data:
